SELECT * FROM fast_food;

-- ✅VERIFYING Dashboard KPI values and SQL Query Values Matching Or Not 

-- TOTAL OVERALL SALES
SELECT SUM(TOTAL_SALES) as total_sales  FROM fast_food;
-- 275230

--Average Sales 
SELECT AVG(TOTAL_SALES) AS AVG_SALES FROM fast_food;

--MAXIMUM ITEM PRICE FROM FASTFOOD
SELECT MAX(ITEM_PRICE) AS MAX_ITEM_PRICE FROM fast_food;

-- total quantity

SELECT SUM(QUANTITY) AS TOTAL_QUANTITY FROM fast_food;

-- NO of Orders
SELECT COUNT(ORDER_ID) AS NO_OF_ORDERS FROM fast_food;

-- SALES BY ITEM
SELECT ITEM_NAME , SUM(TOTAL_SALES) AS SALES  FROM fast_food 
GROUP BY ITEM_NAME ORDER BY SALES DESC ;

-- Sales By Time (ex : - Afternoon)

SELECT TIME_SALES , SUM(TOTAL_SALES) AS SALES  FROM fast_food 
GROUP BY TIME_SALES ORDER BY SALES DESC ;

-- GENDER DISTRIBUTION

SELECT RECEIVED_BY,
COUNT(*) GENDER_COUNT
FROM fast_food
GROUP BY RECEIVED_BY ORDER BY GENDER_COUNT DESC;

-----------------------------------------------------------
--COFFEE DETAILS

-- Coffee total sales KPI
SELECT SUM(TOTAL_SALES) AS TOTAL_SALES_COFFEE FROM fast_food WHERE item_name ='Cold Coffee';

-- cold coffee Avg Sales
SELECT AVG(TOTAL_SALES) AS AVG_COFFEE_SALES FROM fast_food WHERE item_name = 'COLD COFFEE';

--ITEM PRICE COLD COFFEE
SELECT TOP 1  ITEM_PRICE FROM fast_food WHERE ITEM_NAME ='COLD COFFEE';

-- COUNT ORDERS

SELECT COUNT(ORDER_ID) AS NO_OF_ORDERS
FROM fast_food WHERE ITEM_NAME ='COLD COFFEE';

-- COFFEE Gender Distribution
SELECT RECEIVED_BY ,COUNT(*) AS RECEIVED_PERSON
FROM fast_food WHERE ITEM_NAME = 'COLD COFFEE' GROUP BY received_by ORDER BY RECEIVED_PERSON DESC;


-- TABLE VALUES (GROUP BY) ITEM_NAME , TIME, QUANTITY , TOTAL SALES
SELECT ITEM_NAME , 
TIME_SALES  , 
SUM(QUANTITY) TOTAL_QUANTITY ,
SUM(TOTAL_SALES) TOTAL_SALES

FROM fast_food
WHERE item_name ='COLD COFFEE'
GROUP BY ITEM_NAME,
TIME_SALES;


-----------------------------------------------------------
--VADAPAV DETAILS

--TOTAL SALES
SELECT SUM(TOTAL_SALES) AS SALES
FROM fast_food WHERE ITEM_NAME ='VADAPAV';

--AVERAGE SALES
SELECT AVG(TOTAL_SALES) AS AVG_SALES
FROM fast_food WHERE ITEM_NAME ='VADAPAV';

-- VADAPAV PRICE
SELECT TOP 1 ITEM_PRICE  FROM fast_food WHERE ITEM_NAME ='VADAPAV';

-- ORDERS
SELECT COUNT(ORDER_ID) AS NO_OF_ORDERS
FROM fast_food WHERE ITEM_NAME ='VADAPAV';

-- GENDER DIST

SELECT RECEIVED_BY ,COUNT(*) AS RECEIVED_PERSON
FROM fast_food WHERE ITEM_NAME = 'VADAPAV' GROUP BY received_by ORDER BY RECEIVED_PERSON DESC;

-- TABLE VALUES (GROUP BY) ITEM_NAME , TIME, QUANTITY , TOTAL SALES
SELECT ITEM_NAME , 
TIME_SALES  , 
SUM(QUANTITY) TOTAL_QUANTITY ,
SUM(TOTAL_SALES) TOTAL_SALES

FROM fast_food
WHERE item_name ='VADAPAV'
GROUP BY ITEM_NAME,
TIME_SALES ORDER BY TOTAL_SALES DESC;

-----------------------------------------------------------
--SUGARCANE JUICE DETAILS

--TOTAL SALES
SELECT SUM(TOTAL_SALES) AS SALES
FROM fast_food WHERE ITEM_NAME ='SUGARCANE JUICE';


--AVERAGE SALES
SELECT AVG(TOTAL_SALES) AS AVG_SALES
FROM fast_food WHERE ITEM_NAME ='SUGARCANE JUICE';

-- JUICE PRICE 
SELECT TOP 1 ITEM_PRICE  FROM fast_food WHERE ITEM_NAME ='SUGARCANE JUICE';

-- ORDERS
SELECT COUNT(ORDER_ID) AS NO_OF_ORDERS
FROM fast_food WHERE ITEM_NAME ='SUGARCANE JUICE';

-- GENDER DIST

SELECT RECEIVED_BY ,COUNT(*) AS RECEIVED_PERSON
FROM fast_food WHERE ITEM_NAME = 'SUGARCANE JUICE' GROUP BY received_by ORDER BY RECEIVED_PERSON DESC;

SELECT 
    RECEIVED_BY,
    COUNT(*) AS RECEIVED_PERSON,
    SUM(COUNT(*)) OVER (ORDER BY COUNT(*) DESC) AS RUNNING_TOTAL
FROM 
    fast_food 
WHERE 
    ITEM_NAME = 'SUGARCANE JUICE' 
GROUP BY 
    RECEIVED_BY 
ORDER BY 
    RECEIVED_PERSON DESC;


-- TABLE VALUES (GROUP BY) ITEM_NAME , TIME, QUANTITY , TOTAL SALES
SELECT ITEM_NAME , 
TIME_SALES  , 
SUM(QUANTITY) TOTAL_QUANTITY ,
SUM(TOTAL_SALES) TOTAL_SALES

FROM fast_food
WHERE item_name ='SUGARCANE JUICE'
GROUP BY ITEM_NAME,
TIME_SALES ORDER BY TOTAL_SALES DESC;


-----------------------------------------------------------
--PANIPURI DETAILS

--TOTAL SALES
SELECT SUM(TOTAL_SALES) AS SALES
FROM fast_food WHERE ITEM_NAME ='PANIPURI';


--AVERAGE SALES
SELECT AVG(TOTAL_SALES) AS AVG_SALES
FROM fast_food WHERE ITEM_NAME ='PANIPURI';

-- PANIPURI PRICE 
SELECT TOP 1 ITEM_PRICE  FROM fast_food WHERE ITEM_NAME ='PANIPURI';

-- ORDERS
SELECT COUNT(ORDER_ID) AS NO_OF_ORDERS
FROM fast_food WHERE ITEM_NAME ='PANIPURI';

-- GENDER DIST

SELECT RECEIVED_BY ,COUNT(*) AS RECEIVED_PERSON,
FROM fast_food WHERE ITEM_NAME = 'PANIPURI' GROUP BY received_by ORDER BY RECEIVED_PERSON DESC;

/*
SELECT 
    RECEIVED_BY,
    COUNT(*) AS RECEIVED_PERSON,
    (COUNT(*) * 100.0 / SUM(COUNT(*)) OVER ()) AS PER
FROM 
    fast_food 
WHERE 
    ITEM_NAME = 'PANIPURI' 
GROUP BY 
    RECEIVED_BY 
ORDER BY 
    RECEIVED_PERSON DESC;
	

SELECT 
    RECEIVED_BY,
    COUNT(*) AS RECEIVED_PERSON,
    SUM(COUNT(*)) OVER (ORDER BY COUNT(*) DESC) AS RUNNING_TOTAL
FROM 
    fast_food 
WHERE 
    ITEM_NAME = 'SUGARCANE JUICE' 
GROUP BY 
    RECEIVED_BY 
ORDER BY 
    RECEIVED_PERSON DESC;
	*/


-- TABLE VALUES (GROUP BY) ITEM_NAME , TIME, QUANTITY , TOTAL SALES
SELECT ITEM_NAME , 
TIME_SALES  , 
SUM(QUANTITY) TOTAL_QUANTITY ,
SUM(TOTAL_SALES) TOTAL_SALES

FROM fast_food
WHERE item_name ='PANIPURI'
GROUP BY ITEM_NAME,
TIME_SALES ORDER BY TOTAL_SALES DESC;

--🥳🥳 ALL VALUES PERFECT 